# Change these first
owner: EddyAnalytics # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Eddy Analytics
    url: https://www.eddy-analytics.org/
  - name: Eddy Analytics Demo
    url: https://app.eddy-analytics.org/

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/EddyAnalytics/eddy-analytics.org/main/assets/img/logo-brand.svg
  name: Eddy Analytics
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/EddyAnalytics/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
